// Package admin owns registration of the administration HTTP bounded context.
package admin

import (
	mw "github.com/gateyes/gateway/internal/handler/middleware"
	"github.com/gin-gonic/gin"
)

type Handler interface {
	CheckProviders(*gin.Context)
	CreateAPIKey(*gin.Context)
	CreatePlugin(*gin.Context)
	CreateProject(*gin.Context)
	CreateProvider(*gin.Context)
	CreateRole(*gin.Context)
	CreateService(*gin.Context)
	CreateServiceSubscription(*gin.Context)
	CreateServiceVersion(*gin.Context)
	CreateTenant(*gin.Context)
	CreateUser(*gin.Context)
	CreateVirtualKey(*gin.Context)
	Dashboard(*gin.Context)
	DeletePlugin(*gin.Context)
	DeleteProject(*gin.Context)
	DeleteProvider(*gin.Context)
	DeleteRole(*gin.Context)
	DeleteService(*gin.Context)
	DeleteTenant(*gin.Context)
	DeleteUser(*gin.Context)
	DeleteVirtualKey(*gin.Context)
	GetAPIKey(*gin.Context)
	GetBudgets(*gin.Context)
	GetCacheSummary(*gin.Context)
	GetCatalog(*gin.Context)
	GetPlugin(*gin.Context)
	GetProject(*gin.Context)
	GetProjectUsage(*gin.Context)
	GetProvider(*gin.Context)
	GetProviderStats(*gin.Context)
	GetProviders(*gin.Context)
	GetResponseDetail(*gin.Context)
	GetResponseTrace(*gin.Context)
	GetRole(*gin.Context)
	GetService(*gin.Context)
	GetServiceSubscription(*gin.Context)
	GetTenant(*gin.Context)
	GetUsageBreakdown(*gin.Context)
	GetUsageSummary(*gin.Context)
	GetUsageTrend(*gin.Context)
	GetUser(*gin.Context)
	GetUserUsage(*gin.Context)
	GetVirtualKey(*gin.Context)
	ListAPIKeys(*gin.Context)
	ListAuditLogs(*gin.Context)
	ListPermissions(*gin.Context)
	ListPlugins(*gin.Context)
	ListProjects(*gin.Context)
	ListResponses(*gin.Context)
	ListRoles(*gin.Context)
	ListServiceSubscriptions(*gin.Context)
	ListServiceVersions(*gin.Context)
	ListServices(*gin.Context)
	ListTenants(*gin.Context)
	ListUsers(*gin.Context)
	ListVirtualKeys(*gin.Context)
	Me(*gin.Context)
	OIDCCallback(*gin.Context)
	OIDCLogin(*gin.Context)
	OIDCLogout(*gin.Context)
	OIDCRefresh(*gin.Context)
	OIDCStatus(*gin.Context)
	PromoteStagedServiceVersion(*gin.Context)
	PublishServiceVersion(*gin.Context)
	ReloadConfig(*gin.Context)
	ReplaceTenantProviders(*gin.Context)
	ResetUserUsage(*gin.Context)
	ReviewServiceSubscription(*gin.Context)
	RevokeAPIKey(*gin.Context)
	RollbackServiceVersion(*gin.Context)
	RotateAPIKey(*gin.Context)
	SyncBudget(*gin.Context)
	SyncRouter(*gin.Context)
	UpdateAPIKey(*gin.Context)
	UpdatePlugin(*gin.Context)
	UpdateProject(*gin.Context)
	UpdateProvider(*gin.Context)
	UpdateRole(*gin.Context)
	UpdateService(*gin.Context)
	UpdateTenant(*gin.Context)
	UpdateUser(*gin.Context)
	UpdateVirtualKey(*gin.Context)
	UploadPlugin(*gin.Context)
}

// RegisterRoutes installs both /admin/v1 and the legacy /admin alias.
func RegisterRoutes(engine *gin.Engine, h Handler, middleware *mw.Middleware) {
	register := func(g *gin.RouterGroup) {
		g.GET("/me", h.Me)
		g.GET("/dashboard", middleware.RequirePermission(mw.PermUsageRead), h.Dashboard)
		g.GET("/catalog", middleware.RequirePermission(mw.PermUsageRead), h.GetCatalog)
		g.GET("/cache/summary", middleware.RequirePermission(mw.PermConfigWrite), h.GetCacheSummary)
		g.GET("/providers", middleware.RequirePermission(mw.PermProviderRead), h.GetProviders)
		g.POST("/providers/check", middleware.RequirePermission(mw.PermProviderRead), h.CheckProviders)
		g.POST("/providers", middleware.RequirePermission(mw.PermProviderWrite), h.CreateProvider)
		g.GET("/providers/:name", middleware.RequirePermission(mw.PermProviderRead), h.GetProvider)
		g.GET("/providers/:name/stats", middleware.RequirePermission(mw.PermProviderRead), h.GetProviderStats)
		g.PUT("/providers/:name", middleware.RequirePermission(mw.PermProviderWrite), h.UpdateProvider)
		g.DELETE("/providers/:name", middleware.RequirePermission(mw.PermProviderWrite), h.DeleteProvider)
		g.GET("/audit", middleware.RequirePermission(mw.PermAuditRead), h.ListAuditLogs)
		g.GET("/services", middleware.RequirePermission(mw.PermServiceRead), h.ListServices)
		g.POST("/services", middleware.RequirePermission(mw.PermServiceWrite), h.CreateService)
		g.GET("/services/:id", middleware.RequirePermission(mw.PermServiceRead), h.GetService)
		g.PUT("/services/:id", middleware.RequirePermission(mw.PermServiceWrite), h.UpdateService)
		g.DELETE("/services/:id", middleware.RequirePermission(mw.PermServiceWrite), h.DeleteService)
		g.GET("/services/:id/versions", middleware.RequirePermission(mw.PermServiceRead), h.ListServiceVersions)
		g.POST("/services/:id/versions", middleware.RequirePermission(mw.PermServiceWrite), h.CreateServiceVersion)
		g.POST("/services/:id/publish", middleware.RequirePermission(mw.PermServiceWrite), h.PublishServiceVersion)
		g.POST("/services/:id/promote", middleware.RequirePermission(mw.PermServiceWrite), h.PromoteStagedServiceVersion)
		g.POST("/services/:id/rollback", middleware.RequirePermission(mw.PermServiceWrite), h.RollbackServiceVersion)
		g.GET("/services/:id/subscriptions", middleware.RequirePermission(mw.PermServiceRead), h.ListServiceSubscriptions)
		g.POST("/services/:id/subscriptions", middleware.RequirePermission(mw.PermServiceWrite), h.CreateServiceSubscription)
		g.GET("/subscriptions/:id", middleware.RequirePermission(mw.PermServiceRead), h.GetServiceSubscription)
		g.POST("/subscriptions/:id/review", middleware.RequirePermission(mw.PermServiceWrite), h.ReviewServiceSubscription)
		g.GET("/plugins", middleware.RequirePermission(mw.PermConfigWrite), h.ListPlugins)
		g.POST("/plugins", middleware.RequirePermission(mw.PermConfigWrite), h.CreatePlugin)
		g.POST("/plugins/upload", middleware.RequirePermission(mw.PermConfigWrite), h.UploadPlugin)
		g.GET("/plugins/:id", middleware.RequirePermission(mw.PermConfigWrite), h.GetPlugin)
		g.PUT("/plugins/:id", middleware.RequirePermission(mw.PermConfigWrite), h.UpdatePlugin)
		g.DELETE("/plugins/:id", middleware.RequirePermission(mw.PermConfigWrite), h.DeletePlugin)
		g.GET("/keys", middleware.RequirePermission(mw.PermAPIKeyRead), h.ListAPIKeys)
		g.POST("/keys", middleware.RequirePermission(mw.PermAPIKeyWrite), h.CreateAPIKey)
		g.GET("/keys/:id", middleware.RequirePermission(mw.PermAPIKeyRead), h.GetAPIKey)
		g.PUT("/keys/:id", middleware.RequirePermission(mw.PermAPIKeyWrite), h.UpdateAPIKey)
		g.POST("/keys/:id/rotate", middleware.RequirePermission(mw.PermAPIKeyWrite), h.RotateAPIKey)
		g.POST("/keys/:id/revoke", middleware.RequirePermission(mw.PermAPIKeyWrite), h.RevokeAPIKey)
		g.GET("/virtual-keys", middleware.RequirePermission(mw.PermVirtualKeyRead), h.ListVirtualKeys)
		g.POST("/virtual-keys", middleware.RequirePermission(mw.PermVirtualKeyWrite), h.CreateVirtualKey)
		g.GET("/virtual-keys/:id", middleware.RequirePermission(mw.PermVirtualKeyRead), h.GetVirtualKey)
		g.PUT("/virtual-keys/:id", middleware.RequirePermission(mw.PermVirtualKeyWrite), h.UpdateVirtualKey)
		g.DELETE("/virtual-keys/:id", middleware.RequirePermission(mw.PermVirtualKeyWrite), h.DeleteVirtualKey)
		g.GET("/users", middleware.RequirePermission(mw.PermUserRead), h.ListUsers)
		g.POST("/users", middleware.RequirePermission(mw.PermUserWrite), h.CreateUser)
		g.GET("/users/:id", middleware.RequirePermission(mw.PermUserRead), h.GetUser)
		g.PUT("/users/:id", middleware.RequirePermission(mw.PermUserWrite), h.UpdateUser)
		g.DELETE("/users/:id", middleware.RequirePermission(mw.PermUserWrite), h.DeleteUser)
		g.POST("/users/:id/reset", middleware.RequirePermission(mw.PermUserWrite), h.ResetUserUsage)
		g.GET("/users/:id/usage", middleware.RequirePermission(mw.PermUsageRead), h.GetUserUsage)
		g.GET("/projects", middleware.RequirePermission(mw.PermProjectRead), h.ListProjects)
		g.POST("/projects", middleware.RequirePermission(mw.PermProjectWrite), h.CreateProject)
		g.GET("/projects/:id", middleware.RequirePermission(mw.PermProjectRead), h.GetProject)
		g.GET("/projects/:id/usage", middleware.RequirePermission(mw.PermUsageRead), h.GetProjectUsage)
		g.PUT("/projects/:id", middleware.RequirePermission(mw.PermProjectWrite), h.UpdateProject)
		g.DELETE("/projects/:id", middleware.RequirePermission(mw.PermProjectWrite), h.DeleteProject)
		g.GET("/responses", middleware.RequirePermission(mw.PermResponseRead), h.ListResponses)
		g.GET("/responses/:id", middleware.RequirePermission(mw.PermResponseRead), h.GetResponseDetail)
		g.GET("/responses/:id/trace", middleware.RequirePermission(mw.PermResponseRead), h.GetResponseTrace)
		g.GET("/budgets", middleware.RequirePermission(mw.PermBudgetRead), h.GetBudgets)
		g.GET("/usage/summary", middleware.RequirePermission(mw.PermUsageRead), h.GetUsageSummary)
		g.GET("/usage/breakdown", middleware.RequirePermission(mw.PermUsageRead), h.GetUsageBreakdown)
		g.GET("/usage/trend", middleware.RequirePermission(mw.PermUsageRead), h.GetUsageTrend)
		g.POST("/reload", middleware.RequirePermission(mw.PermConfigWrite), h.ReloadConfig)
		g.POST("/sync/router", middleware.RequirePermission(mw.PermConfigWrite), h.SyncRouter)
		g.POST("/sync/budget", middleware.RequirePermission(mw.PermConfigWrite), h.SyncBudget)
		g.GET("/roles", middleware.RequirePermission(mw.PermConfigWrite), h.ListRoles)
		g.POST("/roles", middleware.RequirePermission(mw.PermConfigWrite), h.CreateRole)
		g.GET("/roles/:id", middleware.RequirePermission(mw.PermConfigWrite), h.GetRole)
		g.PUT("/roles/:id", middleware.RequirePermission(mw.PermConfigWrite), h.UpdateRole)
		g.DELETE("/roles/:id", middleware.RequirePermission(mw.PermConfigWrite), h.DeleteRole)
		g.GET("/permissions", middleware.RequirePermission(mw.PermConfigWrite), h.ListPermissions)
	}

	for _, prefix := range []string{"/admin/v1", "/admin"} {
		g := engine.Group(prefix)
		g.Use(func(c *gin.Context) { c.Set("middleware", middleware); c.Next() })
		g.Use(middleware.AdminAuth())
		register(g)
	}

	auth := engine.Group("/admin/auth")
	auth.Use(func(c *gin.Context) { c.Set("middleware", middleware); c.Next() })
	auth.GET("/oidc/status", h.OIDCStatus)
	auth.GET("/oidc/login", h.OIDCLogin)
	auth.GET("/callback", h.OIDCCallback)
	auth.POST("/refresh", h.OIDCRefresh)
	auth.POST("/logout", middleware.AdminAuth(), h.OIDCLogout)

	for _, prefix := range []string{"/admin/v1/tenants", "/admin/tenants"} {
		g := engine.Group(prefix)
		g.Use(func(c *gin.Context) { c.Set("middleware", middleware); c.Next() })
		g.Use(middleware.AdminAuth())
		// Preserve the legacy group-level write gate; individual routes add
		// their read/write permission checks on top of it.
		g.Use(middleware.RequirePermission(mw.PermTenantWrite))
		g.GET("", middleware.RequirePermission(mw.PermTenantRead), h.ListTenants)
		g.POST("", middleware.RequirePermission(mw.PermTenantWrite), h.CreateTenant)
		g.GET("/:id", middleware.RequirePermission(mw.PermTenantRead), h.GetTenant)
		g.PUT("/:id", middleware.RequirePermission(mw.PermTenantWrite), h.UpdateTenant)
		g.DELETE("/:id", middleware.RequirePermission(mw.PermTenantWrite), h.DeleteTenant)
		g.POST("/:id/providers", middleware.RequirePermission(mw.PermTenantWrite), h.ReplaceTenantProviders)
	}
}
