// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/workflow/v1/workflow.proto

package workflowv1

import (
	v1 "github.com/gateyes/gateway/pkg/runtime/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED         WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_PENDING             WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_RUNNING             WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_SUCCEEDED           WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_PARTIALLY_SUCCEEDED WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_FAILED              WorkflowStatus = 5
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED           WorkflowStatus = 6
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_PENDING",
		2: "WORKFLOW_STATUS_RUNNING",
		3: "WORKFLOW_STATUS_SUCCEEDED",
		4: "WORKFLOW_STATUS_PARTIALLY_SUCCEEDED",
		5: "WORKFLOW_STATUS_FAILED",
		6: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED":         0,
		"WORKFLOW_STATUS_PENDING":             1,
		"WORKFLOW_STATUS_RUNNING":             2,
		"WORKFLOW_STATUS_SUCCEEDED":           3,
		"WORKFLOW_STATUS_PARTIALLY_SUCCEEDED": 4,
		"WORKFLOW_STATUS_FAILED":              5,
		"WORKFLOW_STATUS_CANCELLED":           6,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_workflow_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_proto_workflow_v1_workflow_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

type WorkflowErrorCode int32

const (
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_UNSPECIFIED     WorkflowErrorCode = 0
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_INVALID_REQUEST WorkflowErrorCode = 1
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_CONFLICT        WorkflowErrorCode = 2
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_NOT_FOUND       WorkflowErrorCode = 3
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_RUNTIME_FAILED  WorkflowErrorCode = 4
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_CANCELLED       WorkflowErrorCode = 5
	WorkflowErrorCode_WORKFLOW_ERROR_CODE_INTERNAL        WorkflowErrorCode = 6
)

// Enum value maps for WorkflowErrorCode.
var (
	WorkflowErrorCode_name = map[int32]string{
		0: "WORKFLOW_ERROR_CODE_UNSPECIFIED",
		1: "WORKFLOW_ERROR_CODE_INVALID_REQUEST",
		2: "WORKFLOW_ERROR_CODE_CONFLICT",
		3: "WORKFLOW_ERROR_CODE_NOT_FOUND",
		4: "WORKFLOW_ERROR_CODE_RUNTIME_FAILED",
		5: "WORKFLOW_ERROR_CODE_CANCELLED",
		6: "WORKFLOW_ERROR_CODE_INTERNAL",
	}
	WorkflowErrorCode_value = map[string]int32{
		"WORKFLOW_ERROR_CODE_UNSPECIFIED":     0,
		"WORKFLOW_ERROR_CODE_INVALID_REQUEST": 1,
		"WORKFLOW_ERROR_CODE_CONFLICT":        2,
		"WORKFLOW_ERROR_CODE_NOT_FOUND":       3,
		"WORKFLOW_ERROR_CODE_RUNTIME_FAILED":  4,
		"WORKFLOW_ERROR_CODE_CANCELLED":       5,
		"WORKFLOW_ERROR_CODE_INTERNAL":        6,
	}
)

func (x WorkflowErrorCode) Enum() *WorkflowErrorCode {
	p := new(WorkflowErrorCode)
	*p = x
	return p
}

func (x WorkflowErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_workflow_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (WorkflowErrorCode) Type() protoreflect.EnumType {
	return &file_proto_workflow_v1_workflow_proto_enumTypes[1]
}

func (x WorkflowErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowErrorCode.Descriptor instead.
func (WorkflowErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

type SchemaVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersion) Reset() {
	*x = SchemaVersion{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersion) ProtoMessage() {}

func (x *SchemaVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersion.ProtoReflect.Descriptor instead.
func (*SchemaVersion) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SchemaVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type WorkflowMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowMetadata) Reset() {
	*x = WorkflowMetadata{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowMetadata) ProtoMessage() {}

func (x *WorkflowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowMetadata.ProtoReflect.Descriptor instead.
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkflowMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkflowMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ExecuteBatchItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       *WorkflowMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ItemId         string                 `protobuf:"bytes,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteBatchItemRequest) Reset() {
	*x = ExecuteBatchItemRequest{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchItemRequest) ProtoMessage() {}

func (x *ExecuteBatchItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchItemRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteBatchItemRequest) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *ExecuteBatchItemRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteBatchItemRequest) GetMetadata() *WorkflowMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteBatchItemRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteBatchItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ExecuteBatchItemRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteBatchItemRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecuteBatchItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *WorkflowMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=gateyes.workflow.v1.WorkflowStatus" json:"status,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *WorkflowErrorDetail   `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchItemResponse) Reset() {
	*x = ExecuteBatchItemResponse{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchItemResponse) ProtoMessage() {}

func (x *ExecuteBatchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchItemResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBatchItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteBatchItemResponse) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *ExecuteBatchItemResponse) GetMetadata() *WorkflowMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteBatchItemResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteBatchItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ExecuteBatchItemResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *ExecuteBatchItemResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteBatchItemResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteBatchItemResponse) GetError() *WorkflowErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetWorkflowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *WorkflowMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusRequest) Reset() {
	*x = GetWorkflowStatusRequest{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusRequest) ProtoMessage() {}

func (x *GetWorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkflowStatusRequest) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *GetWorkflowStatusRequest) GetMetadata() *WorkflowMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetWorkflowStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata       *WorkflowMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status         WorkflowStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=gateyes.workflow.v1.WorkflowStatus" json:"status,omitempty"`
	TotalItems     uint64                 `protobuf:"varint,5,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CompletedItems uint64                 `protobuf:"varint,6,opt,name=completed_items,json=completedItems,proto3" json:"completed_items,omitempty"`
	FailedItems    uint64                 `protobuf:"varint,7,opt,name=failed_items,json=failedItems,proto3" json:"failed_items,omitempty"`
	Error          *WorkflowErrorDetail   `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWorkflowStatusResponse) Reset() {
	*x = GetWorkflowStatusResponse{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusResponse) ProtoMessage() {}

func (x *GetWorkflowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowStatusResponse) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *GetWorkflowStatusResponse) GetMetadata() *WorkflowMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetWorkflowStatusResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowStatusResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *GetWorkflowStatusResponse) GetTotalItems() uint64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GetWorkflowStatusResponse) GetCompletedItems() uint64 {
	if x != nil {
		return x.CompletedItems
	}
	return 0
}

func (x *GetWorkflowStatusResponse) GetFailedItems() uint64 {
	if x != nil {
		return x.FailedItems
	}
	return 0
}

func (x *GetWorkflowStatusResponse) GetError() *WorkflowErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type WorkflowErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          WorkflowErrorCode      `protobuf:"varint,1,opt,name=code,proto3,enum=gateyes.workflow.v1.WorkflowErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RuntimeError  *v1.RuntimeErrorDetail `protobuf:"bytes,4,opt,name=runtime_error,json=runtimeError,proto3" json:"runtime_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowErrorDetail) Reset() {
	*x = WorkflowErrorDetail{}
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowErrorDetail) ProtoMessage() {}

func (x *WorkflowErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowErrorDetail.ProtoReflect.Descriptor instead.
func (*WorkflowErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_workflow_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowErrorDetail) GetCode() WorkflowErrorCode {
	if x != nil {
		return x.Code
	}
	return WorkflowErrorCode_WORKFLOW_ERROR_CODE_UNSPECIFIED
}

func (x *WorkflowErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *WorkflowErrorDetail) GetRuntimeError() *v1.RuntimeErrorDetail {
	if x != nil {
		return x.RuntimeError
	}
	return nil
}

var File_proto_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_proto_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	" proto/workflow/v1/workflow.proto\x12\x13gateyes.workflow.v1\x1a(proto/runtime/v1/inference_runtime.proto\";\n" +
	"\rSchemaVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"i\n" +
	"\x10WorkflowMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xc7\x02\n" +
	"\x17ExecuteBatchItemRequest\x12I\n" +
	"\x0eschema_version\x18\x01 \x01(\v2\".gateyes.workflow.v1.SchemaVersionR\rschemaVersion\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12A\n" +
	"\bmetadata\x18\x03 \x01(\v2%.gateyes.workflow.v1.WorkflowMetadataR\bmetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\aitem_id\x18\x05 \x01(\tR\x06itemId\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\x9c\x03\n" +
	"\x18ExecuteBatchItemResponse\x12I\n" +
	"\x0eschema_version\x18\x01 \x01(\v2\".gateyes.workflow.v1.SchemaVersionR\rschemaVersion\x12A\n" +
	"\bmetadata\x18\x02 \x01(\v2%.gateyes.workflow.v1.WorkflowMetadataR\bmetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.gateyes.workflow.v1.WorkflowStatusR\x06status\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12>\n" +
	"\x05error\x18\b \x01(\v2(.gateyes.workflow.v1.WorkflowErrorDetailR\x05error\"\xc9\x01\n" +
	"\x18GetWorkflowStatusRequest\x12I\n" +
	"\x0eschema_version\x18\x01 \x01(\v2\".gateyes.workflow.v1.SchemaVersionR\rschemaVersion\x12A\n" +
	"\bmetadata\x18\x02 \x01(\v2%.gateyes.workflow.v1.WorkflowMetadataR\bmetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\"\xb4\x03\n" +
	"\x19GetWorkflowStatusResponse\x12I\n" +
	"\x0eschema_version\x18\x01 \x01(\v2\".gateyes.workflow.v1.SchemaVersionR\rschemaVersion\x12A\n" +
	"\bmetadata\x18\x02 \x01(\v2%.gateyes.workflow.v1.WorkflowMetadataR\bmetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.gateyes.workflow.v1.WorkflowStatusR\x06status\x12\x1f\n" +
	"\vtotal_items\x18\x05 \x01(\x04R\n" +
	"totalItems\x12'\n" +
	"\x0fcompleted_items\x18\x06 \x01(\x04R\x0ecompletedItems\x12!\n" +
	"\ffailed_items\x18\a \x01(\x04R\vfailedItems\x12>\n" +
	"\x05error\x18\b \x01(\v2(.gateyes.workflow.v1.WorkflowErrorDetailR\x05error\"\xd6\x01\n" +
	"\x13WorkflowErrorDetail\x12:\n" +
	"\x04code\x18\x01 \x01(\x0e2&.gateyes.workflow.v1.WorkflowErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12K\n" +
	"\rruntime_error\x18\x04 \x01(\v2&.gateyes.runtime.v1.RuntimeErrorDetailR\fruntimeError*\xee\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_SUCCEEDED\x10\x03\x12'\n" +
	"#WORKFLOW_STATUS_PARTIALLY_SUCCEEDED\x10\x04\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x05\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x06*\x93\x02\n" +
	"\x11WorkflowErrorCode\x12#\n" +
	"\x1fWORKFLOW_ERROR_CODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#WORKFLOW_ERROR_CODE_INVALID_REQUEST\x10\x01\x12 \n" +
	"\x1cWORKFLOW_ERROR_CODE_CONFLICT\x10\x02\x12!\n" +
	"\x1dWORKFLOW_ERROR_CODE_NOT_FOUND\x10\x03\x12&\n" +
	"\"WORKFLOW_ERROR_CODE_RUNTIME_FAILED\x10\x04\x12!\n" +
	"\x1dWORKFLOW_ERROR_CODE_CANCELLED\x10\x05\x12 \n" +
	"\x1cWORKFLOW_ERROR_CODE_INTERNAL\x10\x062\xf6\x01\n" +
	"\x0fWorkflowService\x12o\n" +
	"\x10ExecuteBatchItem\x12,.gateyes.workflow.v1.ExecuteBatchItemRequest\x1a-.gateyes.workflow.v1.ExecuteBatchItemResponse\x12r\n" +
	"\x11GetWorkflowStatus\x12-.gateyes.workflow.v1.GetWorkflowStatusRequest\x1a..gateyes.workflow.v1.GetWorkflowStatusResponseB7Z5github.com/gateyes/gateway/pkg/workflow/v1;workflowv1b\x06proto3"

var (
	file_proto_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_proto_workflow_v1_workflow_proto_rawDescData []byte
)

func file_proto_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_proto_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_proto_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workflow_v1_workflow_proto_rawDesc), len(file_proto_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_proto_workflow_v1_workflow_proto_rawDescData
}

var file_proto_workflow_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_workflow_v1_workflow_proto_goTypes = []any{
	(WorkflowStatus)(0),               // 0: gateyes.workflow.v1.WorkflowStatus
	(WorkflowErrorCode)(0),            // 1: gateyes.workflow.v1.WorkflowErrorCode
	(*SchemaVersion)(nil),             // 2: gateyes.workflow.v1.SchemaVersion
	(*WorkflowMetadata)(nil),          // 3: gateyes.workflow.v1.WorkflowMetadata
	(*ExecuteBatchItemRequest)(nil),   // 4: gateyes.workflow.v1.ExecuteBatchItemRequest
	(*ExecuteBatchItemResponse)(nil),  // 5: gateyes.workflow.v1.ExecuteBatchItemResponse
	(*GetWorkflowStatusRequest)(nil),  // 6: gateyes.workflow.v1.GetWorkflowStatusRequest
	(*GetWorkflowStatusResponse)(nil), // 7: gateyes.workflow.v1.GetWorkflowStatusResponse
	(*WorkflowErrorDetail)(nil),       // 8: gateyes.workflow.v1.WorkflowErrorDetail
	(*v1.RuntimeErrorDetail)(nil),     // 9: gateyes.runtime.v1.RuntimeErrorDetail
}
var file_proto_workflow_v1_workflow_proto_depIdxs = []int32{
	2,  // 0: gateyes.workflow.v1.ExecuteBatchItemRequest.schema_version:type_name -> gateyes.workflow.v1.SchemaVersion
	3,  // 1: gateyes.workflow.v1.ExecuteBatchItemRequest.metadata:type_name -> gateyes.workflow.v1.WorkflowMetadata
	2,  // 2: gateyes.workflow.v1.ExecuteBatchItemResponse.schema_version:type_name -> gateyes.workflow.v1.SchemaVersion
	3,  // 3: gateyes.workflow.v1.ExecuteBatchItemResponse.metadata:type_name -> gateyes.workflow.v1.WorkflowMetadata
	0,  // 4: gateyes.workflow.v1.ExecuteBatchItemResponse.status:type_name -> gateyes.workflow.v1.WorkflowStatus
	8,  // 5: gateyes.workflow.v1.ExecuteBatchItemResponse.error:type_name -> gateyes.workflow.v1.WorkflowErrorDetail
	2,  // 6: gateyes.workflow.v1.GetWorkflowStatusRequest.schema_version:type_name -> gateyes.workflow.v1.SchemaVersion
	3,  // 7: gateyes.workflow.v1.GetWorkflowStatusRequest.metadata:type_name -> gateyes.workflow.v1.WorkflowMetadata
	2,  // 8: gateyes.workflow.v1.GetWorkflowStatusResponse.schema_version:type_name -> gateyes.workflow.v1.SchemaVersion
	3,  // 9: gateyes.workflow.v1.GetWorkflowStatusResponse.metadata:type_name -> gateyes.workflow.v1.WorkflowMetadata
	0,  // 10: gateyes.workflow.v1.GetWorkflowStatusResponse.status:type_name -> gateyes.workflow.v1.WorkflowStatus
	8,  // 11: gateyes.workflow.v1.GetWorkflowStatusResponse.error:type_name -> gateyes.workflow.v1.WorkflowErrorDetail
	1,  // 12: gateyes.workflow.v1.WorkflowErrorDetail.code:type_name -> gateyes.workflow.v1.WorkflowErrorCode
	9,  // 13: gateyes.workflow.v1.WorkflowErrorDetail.runtime_error:type_name -> gateyes.runtime.v1.RuntimeErrorDetail
	4,  // 14: gateyes.workflow.v1.WorkflowService.ExecuteBatchItem:input_type -> gateyes.workflow.v1.ExecuteBatchItemRequest
	6,  // 15: gateyes.workflow.v1.WorkflowService.GetWorkflowStatus:input_type -> gateyes.workflow.v1.GetWorkflowStatusRequest
	5,  // 16: gateyes.workflow.v1.WorkflowService.ExecuteBatchItem:output_type -> gateyes.workflow.v1.ExecuteBatchItemResponse
	7,  // 17: gateyes.workflow.v1.WorkflowService.GetWorkflowStatus:output_type -> gateyes.workflow.v1.GetWorkflowStatusResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_workflow_v1_workflow_proto_init() }
func file_proto_workflow_v1_workflow_proto_init() {
	if File_proto_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workflow_v1_workflow_proto_rawDesc), len(file_proto_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_proto_workflow_v1_workflow_proto_depIdxs,
		EnumInfos:         file_proto_workflow_v1_workflow_proto_enumTypes,
		MessageInfos:      file_proto_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_proto_workflow_v1_workflow_proto = out.File
	file_proto_workflow_v1_workflow_proto_goTypes = nil
	file_proto_workflow_v1_workflow_proto_depIdxs = nil
}
