// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/runtime/v1/inference_runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeErrorDomain int32

const (
	RuntimeErrorDomain_RUNTIME_ERROR_DOMAIN_UNSPECIFIED   RuntimeErrorDomain = 0
	RuntimeErrorDomain_RUNTIME_ERROR_DOMAIN_PROVIDER      RuntimeErrorDomain = 1
	RuntimeErrorDomain_RUNTIME_ERROR_DOMAIN_INTERNAL_RPC  RuntimeErrorDomain = 2
	RuntimeErrorDomain_RUNTIME_ERROR_DOMAIN_CONFIGURATION RuntimeErrorDomain = 3
)

// Enum value maps for RuntimeErrorDomain.
var (
	RuntimeErrorDomain_name = map[int32]string{
		0: "RUNTIME_ERROR_DOMAIN_UNSPECIFIED",
		1: "RUNTIME_ERROR_DOMAIN_PROVIDER",
		2: "RUNTIME_ERROR_DOMAIN_INTERNAL_RPC",
		3: "RUNTIME_ERROR_DOMAIN_CONFIGURATION",
	}
	RuntimeErrorDomain_value = map[string]int32{
		"RUNTIME_ERROR_DOMAIN_UNSPECIFIED":   0,
		"RUNTIME_ERROR_DOMAIN_PROVIDER":      1,
		"RUNTIME_ERROR_DOMAIN_INTERNAL_RPC":  2,
		"RUNTIME_ERROR_DOMAIN_CONFIGURATION": 3,
	}
)

func (x RuntimeErrorDomain) Enum() *RuntimeErrorDomain {
	p := new(RuntimeErrorDomain)
	*p = x
	return p
}

func (x RuntimeErrorDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeErrorDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runtime_v1_inference_runtime_proto_enumTypes[0].Descriptor()
}

func (RuntimeErrorDomain) Type() protoreflect.EnumType {
	return &file_proto_runtime_v1_inference_runtime_proto_enumTypes[0]
}

func (x RuntimeErrorDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeErrorDomain.Descriptor instead.
func (RuntimeErrorDomain) EnumDescriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{0}
}

type RuntimeErrorCode int32

const (
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSPECIFIED       RuntimeErrorCode = 0
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INVALID_REQUEST   RuntimeErrorCode = 1
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNAUTHENTICATED   RuntimeErrorCode = 2
	RuntimeErrorCode_RUNTIME_ERROR_CODE_PERMISSION_DENIED RuntimeErrorCode = 3
	RuntimeErrorCode_RUNTIME_ERROR_CODE_NOT_FOUND         RuntimeErrorCode = 4
	RuntimeErrorCode_RUNTIME_ERROR_CODE_RATE_LIMITED      RuntimeErrorCode = 5
	RuntimeErrorCode_RUNTIME_ERROR_CODE_TIMEOUT           RuntimeErrorCode = 6
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNAVAILABLE       RuntimeErrorCode = 7
	RuntimeErrorCode_RUNTIME_ERROR_CODE_CANCELLED         RuntimeErrorCode = 8
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INTERNAL          RuntimeErrorCode = 9
)

// Enum value maps for RuntimeErrorCode.
var (
	RuntimeErrorCode_name = map[int32]string{
		0: "RUNTIME_ERROR_CODE_UNSPECIFIED",
		1: "RUNTIME_ERROR_CODE_INVALID_REQUEST",
		2: "RUNTIME_ERROR_CODE_UNAUTHENTICATED",
		3: "RUNTIME_ERROR_CODE_PERMISSION_DENIED",
		4: "RUNTIME_ERROR_CODE_NOT_FOUND",
		5: "RUNTIME_ERROR_CODE_RATE_LIMITED",
		6: "RUNTIME_ERROR_CODE_TIMEOUT",
		7: "RUNTIME_ERROR_CODE_UNAVAILABLE",
		8: "RUNTIME_ERROR_CODE_CANCELLED",
		9: "RUNTIME_ERROR_CODE_INTERNAL",
	}
	RuntimeErrorCode_value = map[string]int32{
		"RUNTIME_ERROR_CODE_UNSPECIFIED":       0,
		"RUNTIME_ERROR_CODE_INVALID_REQUEST":   1,
		"RUNTIME_ERROR_CODE_UNAUTHENTICATED":   2,
		"RUNTIME_ERROR_CODE_PERMISSION_DENIED": 3,
		"RUNTIME_ERROR_CODE_NOT_FOUND":         4,
		"RUNTIME_ERROR_CODE_RATE_LIMITED":      5,
		"RUNTIME_ERROR_CODE_TIMEOUT":           6,
		"RUNTIME_ERROR_CODE_UNAVAILABLE":       7,
		"RUNTIME_ERROR_CODE_CANCELLED":         8,
		"RUNTIME_ERROR_CODE_INTERNAL":          9,
	}
)

func (x RuntimeErrorCode) Enum() *RuntimeErrorCode {
	p := new(RuntimeErrorCode)
	*p = x
	return p
}

func (x RuntimeErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runtime_v1_inference_runtime_proto_enumTypes[1].Descriptor()
}

func (RuntimeErrorCode) Type() protoreflect.EnumType {
	return &file_proto_runtime_v1_inference_runtime_proto_enumTypes[1]
}

func (x RuntimeErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeErrorCode.Descriptor instead.
func (RuntimeErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{1}
}

type SchemaVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersion) Reset() {
	*x = SchemaVersion{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersion) ProtoMessage() {}

func (x *SchemaVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersion.ProtoReflect.Descriptor instead.
func (*SchemaVersion) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SchemaVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type TraceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,3,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,4,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceMetadata) Reset() {
	*x = TraceMetadata{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceMetadata) ProtoMessage() {}

func (x *TraceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceMetadata.ProtoReflect.Descriptor instead.
func (*TraceMetadata) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *TraceMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TraceMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceMetadata) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceMetadata) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *TraceMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TraceMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       *TraceMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Surface        string                 `protobuf:"bytes,5,opt,name=surface,proto3" json:"surface,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *ExecuteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRequest) GetMetadata() *TraceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecuteRequest) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *ExecuteRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *TraceMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	Error         *RuntimeErrorDetail    `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *ExecuteResponse) GetMetadata() *TraceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExecuteResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ExecuteResponse) GetError() *RuntimeErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ExecuteStreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       *TraceMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Surface        string                 `protobuf:"bytes,5,opt,name=surface,proto3" json:"surface,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteStreamRequest) Reset() {
	*x = ExecuteStreamRequest{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamRequest) ProtoMessage() {}

func (x *ExecuteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteStreamRequest) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *ExecuteStreamRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteStreamRequest) GetMetadata() *TraceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteStreamRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecuteStreamRequest) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *ExecuteStreamRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecuteStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *TraceMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Terminal      bool                   `protobuf:"varint,6,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	Error         *RuntimeErrorDetail    `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStreamResponse) Reset() {
	*x = ExecuteStreamResponse{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamResponse) ProtoMessage() {}

func (x *ExecuteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamResponse.ProtoReflect.Descriptor instead.
func (*ExecuteStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteStreamResponse) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *ExecuteStreamResponse) GetMetadata() *TraceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteStreamResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ExecuteStreamResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteStreamResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteStreamResponse) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *ExecuteStreamResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ExecuteStreamResponse) GetError() *RuntimeErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   uint64                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *Usage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type RuntimeErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        RuntimeErrorDomain     `protobuf:"varint,1,opt,name=domain,proto3,enum=gateyes.runtime.v1.RuntimeErrorDomain" json:"domain,omitempty"`
	Code          RuntimeErrorCode       `protobuf:"varint,2,opt,name=code,proto3,enum=gateyes.runtime.v1.RuntimeErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeErrorDetail) Reset() {
	*x = RuntimeErrorDetail{}
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeErrorDetail) ProtoMessage() {}

func (x *RuntimeErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_inference_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeErrorDetail.ProtoReflect.Descriptor instead.
func (*RuntimeErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeErrorDetail) GetDomain() RuntimeErrorDomain {
	if x != nil {
		return x.Domain
	}
	return RuntimeErrorDomain_RUNTIME_ERROR_DOMAIN_UNSPECIFIED
}

func (x *RuntimeErrorDetail) GetCode() RuntimeErrorCode {
	if x != nil {
		return x.Code
	}
	return RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSPECIFIED
}

func (x *RuntimeErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RuntimeErrorDetail) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_proto_runtime_v1_inference_runtime_proto protoreflect.FileDescriptor

const file_proto_runtime_v1_inference_runtime_proto_rawDesc = "" +
	"\n" +
	"(proto/runtime/v1/inference_runtime.proto\x12\x12gateyes.runtime.v1\";\n" +
	"\rSchemaVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"\xc4\x01\n" +
	"\rTraceMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x03 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x04 \x01(\tR\fparentSpanId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"\xaf\x02\n" +
	"\x0eExecuteRequest\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.runtime.v1.SchemaVersionR\rschemaVersion\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12=\n" +
	"\bmetadata\x18\x03 \x01(\v2!.gateyes.runtime.v1.TraceMetadataR\bmetadata\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x18\n" +
	"\asurface\x18\x05 \x01(\tR\asurface\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\xe2\x02\n" +
	"\x0fExecuteResponse\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.runtime.v1.SchemaVersionR\rschemaVersion\x12=\n" +
	"\bmetadata\x18\x02 \x01(\v2!.gateyes.runtime.v1.TraceMetadataR\bmetadata\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12/\n" +
	"\x05usage\x18\x06 \x01(\v2\x19.gateyes.runtime.v1.UsageR\x05usage\x12<\n" +
	"\x05error\x18\a \x01(\v2&.gateyes.runtime.v1.RuntimeErrorDetailR\x05error\"\xb5\x02\n" +
	"\x14ExecuteStreamRequest\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.runtime.v1.SchemaVersionR\rschemaVersion\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12=\n" +
	"\bmetadata\x18\x03 \x01(\v2!.gateyes.runtime.v1.TraceMetadataR\bmetadata\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x18\n" +
	"\asurface\x18\x05 \x01(\tR\asurface\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\x84\x03\n" +
	"\x15ExecuteStreamResponse\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.runtime.v1.SchemaVersionR\rschemaVersion\x12=\n" +
	"\bmetadata\x18\x02 \x01(\v2!.gateyes.runtime.v1.TraceMetadataR\bmetadata\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1a\n" +
	"\bterminal\x18\x06 \x01(\bR\bterminal\x12/\n" +
	"\x05usage\x18\a \x01(\v2\x19.gateyes.runtime.v1.UsageR\x05usage\x12<\n" +
	"\x05error\x18\b \x01(\v2&.gateyes.runtime.v1.RuntimeErrorDetailR\x05error\"r\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x04R\vtotalTokens\"\xe2\x01\n" +
	"\x12RuntimeErrorDetail\x12>\n" +
	"\x06domain\x18\x01 \x01(\x0e2&.gateyes.runtime.v1.RuntimeErrorDomainR\x06domain\x128\n" +
	"\x04code\x18\x02 \x01(\x0e2$.gateyes.runtime.v1.RuntimeErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider*\xac\x01\n" +
	"\x12RuntimeErrorDomain\x12$\n" +
	" RUNTIME_ERROR_DOMAIN_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dRUNTIME_ERROR_DOMAIN_PROVIDER\x10\x01\x12%\n" +
	"!RUNTIME_ERROR_DOMAIN_INTERNAL_RPC\x10\x02\x12&\n" +
	"\"RUNTIME_ERROR_DOMAIN_CONFIGURATION\x10\x03*\xfe\x02\n" +
	"\x10RuntimeErrorCode\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"RUNTIME_ERROR_CODE_INVALID_REQUEST\x10\x01\x12&\n" +
	"\"RUNTIME_ERROR_CODE_UNAUTHENTICATED\x10\x02\x12(\n" +
	"$RUNTIME_ERROR_CODE_PERMISSION_DENIED\x10\x03\x12 \n" +
	"\x1cRUNTIME_ERROR_CODE_NOT_FOUND\x10\x04\x12#\n" +
	"\x1fRUNTIME_ERROR_CODE_RATE_LIMITED\x10\x05\x12\x1e\n" +
	"\x1aRUNTIME_ERROR_CODE_TIMEOUT\x10\x06\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNAVAILABLE\x10\a\x12 \n" +
	"\x1cRUNTIME_ERROR_CODE_CANCELLED\x10\b\x12\x1f\n" +
	"\x1bRUNTIME_ERROR_CODE_INTERNAL\x10\t2\xd5\x01\n" +
	"\x17InferenceRuntimeService\x12R\n" +
	"\aExecute\x12\".gateyes.runtime.v1.ExecuteRequest\x1a#.gateyes.runtime.v1.ExecuteResponse\x12f\n" +
	"\rExecuteStream\x12(.gateyes.runtime.v1.ExecuteStreamRequest\x1a).gateyes.runtime.v1.ExecuteStreamResponse0\x01B5Z3github.com/gateyes/gateway/pkg/runtime/v1;runtimev1b\x06proto3"

var (
	file_proto_runtime_v1_inference_runtime_proto_rawDescOnce sync.Once
	file_proto_runtime_v1_inference_runtime_proto_rawDescData []byte
)

func file_proto_runtime_v1_inference_runtime_proto_rawDescGZIP() []byte {
	file_proto_runtime_v1_inference_runtime_proto_rawDescOnce.Do(func() {
		file_proto_runtime_v1_inference_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runtime_v1_inference_runtime_proto_rawDesc), len(file_proto_runtime_v1_inference_runtime_proto_rawDesc)))
	})
	return file_proto_runtime_v1_inference_runtime_proto_rawDescData
}

var file_proto_runtime_v1_inference_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_runtime_v1_inference_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_runtime_v1_inference_runtime_proto_goTypes = []any{
	(RuntimeErrorDomain)(0),       // 0: gateyes.runtime.v1.RuntimeErrorDomain
	(RuntimeErrorCode)(0),         // 1: gateyes.runtime.v1.RuntimeErrorCode
	(*SchemaVersion)(nil),         // 2: gateyes.runtime.v1.SchemaVersion
	(*TraceMetadata)(nil),         // 3: gateyes.runtime.v1.TraceMetadata
	(*ExecuteRequest)(nil),        // 4: gateyes.runtime.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 5: gateyes.runtime.v1.ExecuteResponse
	(*ExecuteStreamRequest)(nil),  // 6: gateyes.runtime.v1.ExecuteStreamRequest
	(*ExecuteStreamResponse)(nil), // 7: gateyes.runtime.v1.ExecuteStreamResponse
	(*Usage)(nil),                 // 8: gateyes.runtime.v1.Usage
	(*RuntimeErrorDetail)(nil),    // 9: gateyes.runtime.v1.RuntimeErrorDetail
}
var file_proto_runtime_v1_inference_runtime_proto_depIdxs = []int32{
	2,  // 0: gateyes.runtime.v1.ExecuteRequest.schema_version:type_name -> gateyes.runtime.v1.SchemaVersion
	3,  // 1: gateyes.runtime.v1.ExecuteRequest.metadata:type_name -> gateyes.runtime.v1.TraceMetadata
	2,  // 2: gateyes.runtime.v1.ExecuteResponse.schema_version:type_name -> gateyes.runtime.v1.SchemaVersion
	3,  // 3: gateyes.runtime.v1.ExecuteResponse.metadata:type_name -> gateyes.runtime.v1.TraceMetadata
	8,  // 4: gateyes.runtime.v1.ExecuteResponse.usage:type_name -> gateyes.runtime.v1.Usage
	9,  // 5: gateyes.runtime.v1.ExecuteResponse.error:type_name -> gateyes.runtime.v1.RuntimeErrorDetail
	2,  // 6: gateyes.runtime.v1.ExecuteStreamRequest.schema_version:type_name -> gateyes.runtime.v1.SchemaVersion
	3,  // 7: gateyes.runtime.v1.ExecuteStreamRequest.metadata:type_name -> gateyes.runtime.v1.TraceMetadata
	2,  // 8: gateyes.runtime.v1.ExecuteStreamResponse.schema_version:type_name -> gateyes.runtime.v1.SchemaVersion
	3,  // 9: gateyes.runtime.v1.ExecuteStreamResponse.metadata:type_name -> gateyes.runtime.v1.TraceMetadata
	8,  // 10: gateyes.runtime.v1.ExecuteStreamResponse.usage:type_name -> gateyes.runtime.v1.Usage
	9,  // 11: gateyes.runtime.v1.ExecuteStreamResponse.error:type_name -> gateyes.runtime.v1.RuntimeErrorDetail
	0,  // 12: gateyes.runtime.v1.RuntimeErrorDetail.domain:type_name -> gateyes.runtime.v1.RuntimeErrorDomain
	1,  // 13: gateyes.runtime.v1.RuntimeErrorDetail.code:type_name -> gateyes.runtime.v1.RuntimeErrorCode
	4,  // 14: gateyes.runtime.v1.InferenceRuntimeService.Execute:input_type -> gateyes.runtime.v1.ExecuteRequest
	6,  // 15: gateyes.runtime.v1.InferenceRuntimeService.ExecuteStream:input_type -> gateyes.runtime.v1.ExecuteStreamRequest
	5,  // 16: gateyes.runtime.v1.InferenceRuntimeService.Execute:output_type -> gateyes.runtime.v1.ExecuteResponse
	7,  // 17: gateyes.runtime.v1.InferenceRuntimeService.ExecuteStream:output_type -> gateyes.runtime.v1.ExecuteStreamResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_runtime_v1_inference_runtime_proto_init() }
func file_proto_runtime_v1_inference_runtime_proto_init() {
	if File_proto_runtime_v1_inference_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runtime_v1_inference_runtime_proto_rawDesc), len(file_proto_runtime_v1_inference_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runtime_v1_inference_runtime_proto_goTypes,
		DependencyIndexes: file_proto_runtime_v1_inference_runtime_proto_depIdxs,
		EnumInfos:         file_proto_runtime_v1_inference_runtime_proto_enumTypes,
		MessageInfos:      file_proto_runtime_v1_inference_runtime_proto_msgTypes,
	}.Build()
	File_proto_runtime_v1_inference_runtime_proto = out.File
	file_proto_runtime_v1_inference_runtime_proto_goTypes = nil
	file_proto_runtime_v1_inference_runtime_proto_depIdxs = nil
}
