// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/runtime/v1/inference_runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceRuntimeService_Execute_FullMethodName       = "/gateyes.runtime.v1.InferenceRuntimeService/Execute"
	InferenceRuntimeService_ExecuteStream_FullMethodName = "/gateyes.runtime.v1.InferenceRuntimeService/ExecuteStream"
)

// InferenceRuntimeServiceClient is the client API for InferenceRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferenceRuntimeService executes provider-facing inference work.
type InferenceRuntimeServiceClient interface {
	// Execute returns one complete inference result.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// ExecuteStream returns ordered inference chunks ending in a terminal chunk.
	ExecuteStream(ctx context.Context, in *ExecuteStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteStreamResponse], error)
}

type inferenceRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceRuntimeServiceClient(cc grpc.ClientConnInterface) InferenceRuntimeServiceClient {
	return &inferenceRuntimeServiceClient{cc}
}

func (c *inferenceRuntimeServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, InferenceRuntimeService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRuntimeServiceClient) ExecuteStream(ctx context.Context, in *ExecuteStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceRuntimeService_ServiceDesc.Streams[0], InferenceRuntimeService_ExecuteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteStreamRequest, ExecuteStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceRuntimeService_ExecuteStreamClient = grpc.ServerStreamingClient[ExecuteStreamResponse]

// InferenceRuntimeServiceServer is the server API for InferenceRuntimeService service.
// All implementations must embed UnimplementedInferenceRuntimeServiceServer
// for forward compatibility.
//
// InferenceRuntimeService executes provider-facing inference work.
type InferenceRuntimeServiceServer interface {
	// Execute returns one complete inference result.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// ExecuteStream returns ordered inference chunks ending in a terminal chunk.
	ExecuteStream(*ExecuteStreamRequest, grpc.ServerStreamingServer[ExecuteStreamResponse]) error
	mustEmbedUnimplementedInferenceRuntimeServiceServer()
}

// UnimplementedInferenceRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceRuntimeServiceServer struct{}

func (UnimplementedInferenceRuntimeServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedInferenceRuntimeServiceServer) ExecuteStream(*ExecuteStreamRequest, grpc.ServerStreamingServer[ExecuteStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedInferenceRuntimeServiceServer) mustEmbedUnimplementedInferenceRuntimeServiceServer() {
}
func (UnimplementedInferenceRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeInferenceRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceRuntimeServiceServer will
// result in compilation errors.
type UnsafeInferenceRuntimeServiceServer interface {
	mustEmbedUnimplementedInferenceRuntimeServiceServer()
}

func RegisterInferenceRuntimeServiceServer(s grpc.ServiceRegistrar, srv InferenceRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceRuntimeService_ServiceDesc, srv)
}

func _InferenceRuntimeService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRuntimeServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRuntimeService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRuntimeServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRuntimeService_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceRuntimeServiceServer).ExecuteStream(m, &grpc.GenericServerStream[ExecuteStreamRequest, ExecuteStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceRuntimeService_ExecuteStreamServer = grpc.ServerStreamingServer[ExecuteStreamResponse]

// InferenceRuntimeService_ServiceDesc is the grpc.ServiceDesc for InferenceRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateyes.runtime.v1.InferenceRuntimeService",
	HandlerType: (*InferenceRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _InferenceRuntimeService_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _InferenceRuntimeService_ExecuteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/runtime/v1/inference_runtime.proto",
}
