CREATE TABLE IF NOT EXISTS users (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	quota INTEGER NOT NULL,
	used INTEGER NOT NULL DEFAULT 0,
	qps INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
