ALTER TABLE tenants ADD COLUMN budget_usd REAL NOT NULL DEFAULT 0;
ALTER TABLE tenants ADD COLUMN spent_usd REAL NOT NULL DEFAULT 0;

ALTER TABLE api_keys ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE api_keys ADD COLUMN allowed_models TEXT NOT NULL DEFAULT '[]';
ALTER TABLE api_keys ADD COLUMN allowed_providers TEXT NOT NULL DEFAULT '[]';
ALTER TABLE api_keys ADD COLUMN rate_limit_qps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE api_keys ADD COLUMN revoked_at TIMESTAMP NULL;

ALTER TABLE responses ADD COLUMN route_trace_body TEXT NOT NULL DEFAULT '';
