{{- if and (ne .Values.platform.mode "operator") .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "gateyes.fullname" . }}
  labels:
    {{- include "gateyes.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    {{- toYaml .Values.monitoring.prometheusRule.groups | nindent 4 }}
{{- end }}
