// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/plugin/v1/gateway.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase defines the fixed lifecycle points in the gateway.
// A plugin may subscribe to one or more phases via its config.
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	// Before the gateway routes the request to an upstream provider.
	// Payload: {"candidates": [...]}
	Phase_PHASE_PRE_ROUTE Phase = 1
	// After the gateway has selected/ordered providers.
	// Payload: {"ordered": [...], "selected": "provider_name"}
	Phase_PHASE_POST_ROUTE Phase = 2
	// Before the request is sent to the upstream provider.
	// Payload: {"request": {...}} (the full upstream request body)
	Phase_PHASE_PRE_UPSTREAM Phase = 3
	// After the upstream response has been received.
	// Payload: {"response": {...}} (the full upstream response body)
	Phase_PHASE_POST_UPSTREAM Phase = 4
	// After the response has been fully streamed/written to the client.
	// Payload: {"request": {...}, "response": {...}, "usage": {...}}
	// This is fire-and-forget; the gateway does not wait for commands.
	Phase_PHASE_AUDIT Phase = 5
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_PRE_ROUTE",
		2: "PHASE_POST_ROUTE",
		3: "PHASE_PRE_UPSTREAM",
		4: "PHASE_POST_UPSTREAM",
		5: "PHASE_AUDIT",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":   0,
		"PHASE_PRE_ROUTE":     1,
		"PHASE_POST_ROUTE":    2,
		"PHASE_PRE_UPSTREAM":  3,
		"PHASE_POST_UPSTREAM": 4,
		"PHASE_AUDIT":         5,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_proto_plugin_v1_gateway_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_v1_gateway_proto_rawDescGZIP(), []int{0}
}

// Action is the instruction the plugin gives to the gateway.
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	// Continue processing without changes.
	Action_ACTION_ALLOW Action = 1
	// Abort the request and return an error to the client.
	// Payload is ignored; reason should be set.
	Action_ACTION_BLOCK Action = 2
	// Replace the current payload with the transformed version.
	// Payload: the new JSON payload for this phase.
	Action_ACTION_TRANSFORM Action = 3
	// Cache hit: the gateway should return the payload directly
	// without going upstream (valid only in pre_upstream).
	Action_ACTION_CACHE_HIT Action = 4
	// Skip further plugins in this phase.
	Action_ACTION_SKIP Action = 5
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ALLOW",
		2: "ACTION_BLOCK",
		3: "ACTION_TRANSFORM",
		4: "ACTION_CACHE_HIT",
		5: "ACTION_SKIP",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ALLOW":       1,
		"ACTION_BLOCK":       2,
		"ACTION_TRANSFORM":   3,
		"ACTION_CACHE_HIT":   4,
		"ACTION_SKIP":        5,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_v1_gateway_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_plugin_v1_gateway_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_v1_gateway_proto_rawDescGZIP(), []int{1}
}

// Event is emitted by the gateway at a fixed lifecycle point.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The lifecycle phase at which this event is fired.
	Phase Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=gateyes.plugin.v1.Phase" json:"phase,omitempty"`
	// Request context (available in all phases).
	Context *Context `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Phase-specific payload (JSON).
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_plugin_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Event) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Context carries request metadata available in all phases.
type Context struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway-generated trace ID.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Tenant identifier.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User / API key identifier.
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Model requested by the client.
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// Whether the request is streaming.
	Stream bool `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	// The provider that was ultimately selected (post_route and later).
	SelectedProvider string `protobuf:"bytes,6,opt,name=selected_provider,json=selectedProvider,proto3" json:"selected_provider,omitempty"`
	// The surface being used ("chat", "responses", "messages").
	Surface       string `protobuf:"bytes,7,opt,name=surface,proto3" json:"surface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_proto_plugin_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Context) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Context) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Context) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Context) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Context) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *Context) GetSelectedProvider() string {
	if x != nil {
		return x.SelectedProvider
	}
	return ""
}

func (x *Context) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

// Command is returned by the plugin to instruct the gateway.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action the gateway should take.
	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=gateyes.plugin.v1.Action" json:"action,omitempty"`
	// Action-specific payload (JSON).
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Human-readable reason (required when action = BLOCK).
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_plugin_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_plugin_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/plugin/v1/gateway.proto\x12\x11gateyes.plugin.v1\"\x87\x01\n" +
	"\x05Event\x12.\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x18.gateyes.plugin.v1.PhaseR\x05phase\x124\n" +
	"\acontext\x18\x02 \x01(\v2\x1a.gateyes.plugin.v1.ContextR\acontext\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xcf\x01\n" +
	"\aContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12+\n" +
	"\x11selected_provider\x18\x06 \x01(\tR\x10selectedProvider\x12\x18\n" +
	"\asurface\x18\a \x01(\tR\asurface\"n\n" +
	"\aCommand\x121\n" +
	"\x06action\x18\x01 \x01(\x0e2\x19.gateyes.plugin.v1.ActionR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*\x8b\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPHASE_PRE_ROUTE\x10\x01\x12\x14\n" +
	"\x10PHASE_POST_ROUTE\x10\x02\x12\x16\n" +
	"\x12PHASE_PRE_UPSTREAM\x10\x03\x12\x17\n" +
	"\x13PHASE_POST_UPSTREAM\x10\x04\x12\x0f\n" +
	"\vPHASE_AUDIT\x10\x05*\x81\x01\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x10\n" +
	"\fACTION_BLOCK\x10\x02\x12\x14\n" +
	"\x10ACTION_TRANSFORM\x10\x03\x12\x14\n" +
	"\x10ACTION_CACHE_HIT\x10\x04\x12\x0f\n" +
	"\vACTION_SKIP\x10\x052T\n" +
	"\rGatewayPlugin\x12C\n" +
	"\aProcess\x12\x18.gateyes.plugin.v1.Event\x1a\x1a.gateyes.plugin.v1.Command(\x010\x01B*Z(github.com/gateyes/gateway/pkg/plugin/v1b\x06proto3"

var (
	file_proto_plugin_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_gateway_proto_rawDescData []byte
)

func file_proto_plugin_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_gateway_proto_rawDesc), len(file_proto_plugin_v1_gateway_proto_rawDesc)))
	})
	return file_proto_plugin_v1_gateway_proto_rawDescData
}

var file_proto_plugin_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_plugin_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_plugin_v1_gateway_proto_goTypes = []any{
	(Phase)(0),      // 0: gateyes.plugin.v1.Phase
	(Action)(0),     // 1: gateyes.plugin.v1.Action
	(*Event)(nil),   // 2: gateyes.plugin.v1.Event
	(*Context)(nil), // 3: gateyes.plugin.v1.Context
	(*Command)(nil), // 4: gateyes.plugin.v1.Command
}
var file_proto_plugin_v1_gateway_proto_depIdxs = []int32{
	0, // 0: gateyes.plugin.v1.Event.phase:type_name -> gateyes.plugin.v1.Phase
	3, // 1: gateyes.plugin.v1.Event.context:type_name -> gateyes.plugin.v1.Context
	1, // 2: gateyes.plugin.v1.Command.action:type_name -> gateyes.plugin.v1.Action
	2, // 3: gateyes.plugin.v1.GatewayPlugin.Process:input_type -> gateyes.plugin.v1.Event
	4, // 4: gateyes.plugin.v1.GatewayPlugin.Process:output_type -> gateyes.plugin.v1.Command
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_gateway_proto_init() }
func file_proto_plugin_v1_gateway_proto_init() {
	if File_proto_plugin_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_gateway_proto_rawDesc), len(file_proto_plugin_v1_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_gateway_proto_depIdxs,
		EnumInfos:         file_proto_plugin_v1_gateway_proto_enumTypes,
		MessageInfos:      file_proto_plugin_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_gateway_proto = out.File
	file_proto_plugin_v1_gateway_proto_goTypes = nil
	file_proto_plugin_v1_gateway_proto_depIdxs = nil
}
