// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/plugin/v1/gateway.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayPlugin_Process_FullMethodName = "/gateyes.plugin.v1.GatewayPlugin/Process"
)

// GatewayPluginClient is the client API for GatewayPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayPlugin is a universal extension interface for all non-routing
// plugin scenarios (cache, audit, transform, guardrail, etc.).
//
// The gateway sends Events at fixed lifecycle points; the plugin
// returns Commands that the gateway then executes (allow, block,
// transform, cache_hit, skip, etc.).
//
// Communication is streaming so that a single plugin instance can
// handle multiple events without paying connection overhead each time.
type GatewayPluginClient interface {
	// Process receives a stream of events and returns a stream of commands.
	// Both sides are half-duplex: the gateway sends an event, the plugin
	// replies with one or more commands, then the gateway may send the
	// next event.
	Process(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Command], error)
}

type gatewayPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayPluginClient(cc grpc.ClientConnInterface) GatewayPluginClient {
	return &gatewayPluginClient{cc}
}

func (c *gatewayPluginClient) Process(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayPlugin_ServiceDesc.Streams[0], GatewayPlugin_Process_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayPlugin_ProcessClient = grpc.BidiStreamingClient[Event, Command]

// GatewayPluginServer is the server API for GatewayPlugin service.
// All implementations must embed UnimplementedGatewayPluginServer
// for forward compatibility.
//
// GatewayPlugin is a universal extension interface for all non-routing
// plugin scenarios (cache, audit, transform, guardrail, etc.).
//
// The gateway sends Events at fixed lifecycle points; the plugin
// returns Commands that the gateway then executes (allow, block,
// transform, cache_hit, skip, etc.).
//
// Communication is streaming so that a single plugin instance can
// handle multiple events without paying connection overhead each time.
type GatewayPluginServer interface {
	// Process receives a stream of events and returns a stream of commands.
	// Both sides are half-duplex: the gateway sends an event, the plugin
	// replies with one or more commands, then the gateway may send the
	// next event.
	Process(grpc.BidiStreamingServer[Event, Command]) error
	mustEmbedUnimplementedGatewayPluginServer()
}

// UnimplementedGatewayPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayPluginServer struct{}

func (UnimplementedGatewayPluginServer) Process(grpc.BidiStreamingServer[Event, Command]) error {
	return status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedGatewayPluginServer) mustEmbedUnimplementedGatewayPluginServer() {}
func (UnimplementedGatewayPluginServer) testEmbeddedByValue()                       {}

// UnsafeGatewayPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayPluginServer will
// result in compilation errors.
type UnsafeGatewayPluginServer interface {
	mustEmbedUnimplementedGatewayPluginServer()
}

func RegisterGatewayPluginServer(s grpc.ServiceRegistrar, srv GatewayPluginServer) {
	// If the following call panics, it indicates UnimplementedGatewayPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayPlugin_ServiceDesc, srv)
}

func _GatewayPlugin_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayPluginServer).Process(&grpc.GenericServerStream[Event, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayPlugin_ProcessServer = grpc.BidiStreamingServer[Event, Command]

// GatewayPlugin_ServiceDesc is the grpc.ServiceDesc for GatewayPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateyes.plugin.v1.GatewayPlugin",
	HandlerType: (*GatewayPluginServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _GatewayPlugin_Process_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin/v1/gateway.proto",
}
