// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/plugin/v1/router.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterPlugin_OrderCandidates_FullMethodName = "/gateyes.plugin.v1.RouterPlugin/OrderCandidates"
)

// RouterPluginClient is the client API for RouterPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RouterPlugin is called by the gateway to decide the order in which
// upstream providers should be tried. The gateway passes the full list
// of candidate providers plus the request context; the plugin returns
// an ordered list of provider names. The first name in the list is the
// preferred provider.
type RouterPluginClient interface {
	OrderCandidates(ctx context.Context, in *OrderCandidatesRequest, opts ...grpc.CallOption) (*OrderCandidatesResponse, error)
}

type routerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterPluginClient(cc grpc.ClientConnInterface) RouterPluginClient {
	return &routerPluginClient{cc}
}

func (c *routerPluginClient) OrderCandidates(ctx context.Context, in *OrderCandidatesRequest, opts ...grpc.CallOption) (*OrderCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCandidatesResponse)
	err := c.cc.Invoke(ctx, RouterPlugin_OrderCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterPluginServer is the server API for RouterPlugin service.
// All implementations must embed UnimplementedRouterPluginServer
// for forward compatibility.
//
// RouterPlugin is called by the gateway to decide the order in which
// upstream providers should be tried. The gateway passes the full list
// of candidate providers plus the request context; the plugin returns
// an ordered list of provider names. The first name in the list is the
// preferred provider.
type RouterPluginServer interface {
	OrderCandidates(context.Context, *OrderCandidatesRequest) (*OrderCandidatesResponse, error)
	mustEmbedUnimplementedRouterPluginServer()
}

// UnimplementedRouterPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterPluginServer struct{}

func (UnimplementedRouterPluginServer) OrderCandidates(context.Context, *OrderCandidatesRequest) (*OrderCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OrderCandidates not implemented")
}
func (UnimplementedRouterPluginServer) mustEmbedUnimplementedRouterPluginServer() {}
func (UnimplementedRouterPluginServer) testEmbeddedByValue()                      {}

// UnsafeRouterPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterPluginServer will
// result in compilation errors.
type UnsafeRouterPluginServer interface {
	mustEmbedUnimplementedRouterPluginServer()
}

func RegisterRouterPluginServer(s grpc.ServiceRegistrar, srv RouterPluginServer) {
	// If the following call panics, it indicates UnimplementedRouterPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterPlugin_ServiceDesc, srv)
}

func _RouterPlugin_OrderCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterPluginServer).OrderCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterPlugin_OrderCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterPluginServer).OrderCandidates(ctx, req.(*OrderCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterPlugin_ServiceDesc is the grpc.ServiceDesc for RouterPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateyes.plugin.v1.RouterPlugin",
	HandlerType: (*RouterPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderCandidates",
			Handler:    _RouterPlugin_OrderCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/v1/router.proto",
}
