// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/plugin/v1/router.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCandidatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The candidate providers available for this request.
	Candidates []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// Context about the current request.
	Context       *RouteContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCandidatesRequest) Reset() {
	*x = OrderCandidatesRequest{}
	mi := &file_proto_plugin_v1_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCandidatesRequest) ProtoMessage() {}

func (x *OrderCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCandidatesRequest.ProtoReflect.Descriptor instead.
func (*OrderCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_router_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCandidatesRequest) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *OrderCandidatesRequest) GetContext() *RouteContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type Candidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider name (e.g. "codexapis").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The model this provider serves.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Routing weight configured in the gateway.
	Weight int32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// Cost per token (input+output average), or 0 if unknown.
	UnitCost float64 `protobuf:"fixed64,4,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	// Current in-flight request count on this provider.
	CurrentLoad int64 `protobuf:"varint,5,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	// Tokens per minute observed on this provider.
	Tpm int64 `protobuf:"varint,6,opt,name=tpm,proto3" json:"tpm,omitempty"`
	// Whether the provider is considered healthy.
	Healthy       bool `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_proto_plugin_v1_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_router_proto_rawDescGZIP(), []int{1}
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Candidate) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Candidate) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Candidate) GetUnitCost() float64 {
	if x != nil {
		return x.UnitCost
	}
	return 0
}

func (x *Candidate) GetCurrentLoad() int64 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *Candidate) GetTpm() int64 {
	if x != nil {
		return x.Tpm
	}
	return 0
}

func (x *Candidate) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type RouteContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model requested by the client.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Session identifier for affinity-aware routing.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The raw user input text (first user message content).
	InputText string `protobuf:"bytes,3,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	// Estimated prompt token count.
	PromptTokens int32 `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	// Whether the request asks for streaming.
	Stream bool `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	// Whether the request includes tool definitions.
	HasTools bool `protobuf:"varint,6,opt,name=has_tools,json=hasTools,proto3" json:"has_tools,omitempty"`
	// Whether the request includes image inputs.
	HasImages bool `protobuf:"varint,7,opt,name=has_images,json=hasImages,proto3" json:"has_images,omitempty"`
	// Whether the request asks for structured output.
	HasStructuredOutput bool `protobuf:"varint,8,opt,name=has_structured_output,json=hasStructuredOutput,proto3" json:"has_structured_output,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RouteContext) Reset() {
	*x = RouteContext{}
	mi := &file_proto_plugin_v1_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteContext) ProtoMessage() {}

func (x *RouteContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteContext.ProtoReflect.Descriptor instead.
func (*RouteContext) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_router_proto_rawDescGZIP(), []int{2}
}

func (x *RouteContext) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RouteContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RouteContext) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

func (x *RouteContext) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *RouteContext) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *RouteContext) GetHasTools() bool {
	if x != nil {
		return x.HasTools
	}
	return false
}

func (x *RouteContext) GetHasImages() bool {
	if x != nil {
		return x.HasImages
	}
	return false
}

func (x *RouteContext) GetHasStructuredOutput() bool {
	if x != nil {
		return x.HasStructuredOutput
	}
	return false
}

type OrderCandidatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered list of provider names. The gateway will try them in this order.
	// If empty, the gateway falls back to its built-in strategy.
	OrderedNames  []string `protobuf:"bytes,1,rep,name=ordered_names,json=orderedNames,proto3" json:"ordered_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCandidatesResponse) Reset() {
	*x = OrderCandidatesResponse{}
	mi := &file_proto_plugin_v1_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCandidatesResponse) ProtoMessage() {}

func (x *OrderCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCandidatesResponse.ProtoReflect.Descriptor instead.
func (*OrderCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_router_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCandidatesResponse) GetOrderedNames() []string {
	if x != nil {
		return x.OrderedNames
	}
	return nil
}

var File_proto_plugin_v1_router_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_router_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/router.proto\x12\x11gateyes.plugin.v1\"\x91\x01\n" +
	"\x16OrderCandidatesRequest\x12<\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1c.gateyes.plugin.v1.CandidateR\n" +
	"candidates\x129\n" +
	"\acontext\x18\x02 \x01(\v2\x1f.gateyes.plugin.v1.RouteContextR\acontext\"\xb9\x01\n" +
	"\tCandidate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12\x1b\n" +
	"\tunit_cost\x18\x04 \x01(\x01R\bunitCost\x12!\n" +
	"\fcurrent_load\x18\x05 \x01(\x03R\vcurrentLoad\x12\x10\n" +
	"\x03tpm\x18\x06 \x01(\x03R\x03tpm\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\"\x8f\x02\n" +
	"\fRouteContext\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"input_text\x18\x03 \x01(\tR\tinputText\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12\x1b\n" +
	"\thas_tools\x18\x06 \x01(\bR\bhasTools\x12\x1d\n" +
	"\n" +
	"has_images\x18\a \x01(\bR\thasImages\x122\n" +
	"\x15has_structured_output\x18\b \x01(\bR\x13hasStructuredOutput\">\n" +
	"\x17OrderCandidatesResponse\x12#\n" +
	"\rordered_names\x18\x01 \x03(\tR\forderedNames2x\n" +
	"\fRouterPlugin\x12h\n" +
	"\x0fOrderCandidates\x12).gateyes.plugin.v1.OrderCandidatesRequest\x1a*.gateyes.plugin.v1.OrderCandidatesResponseB*Z(github.com/gateyes/gateway/pkg/plugin/v1b\x06proto3"

var (
	file_proto_plugin_v1_router_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_router_proto_rawDescData []byte
)

func file_proto_plugin_v1_router_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_router_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_router_proto_rawDesc), len(file_proto_plugin_v1_router_proto_rawDesc)))
	})
	return file_proto_plugin_v1_router_proto_rawDescData
}

var file_proto_plugin_v1_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_plugin_v1_router_proto_goTypes = []any{
	(*OrderCandidatesRequest)(nil),  // 0: gateyes.plugin.v1.OrderCandidatesRequest
	(*Candidate)(nil),               // 1: gateyes.plugin.v1.Candidate
	(*RouteContext)(nil),            // 2: gateyes.plugin.v1.RouteContext
	(*OrderCandidatesResponse)(nil), // 3: gateyes.plugin.v1.OrderCandidatesResponse
}
var file_proto_plugin_v1_router_proto_depIdxs = []int32{
	1, // 0: gateyes.plugin.v1.OrderCandidatesRequest.candidates:type_name -> gateyes.plugin.v1.Candidate
	2, // 1: gateyes.plugin.v1.OrderCandidatesRequest.context:type_name -> gateyes.plugin.v1.RouteContext
	0, // 2: gateyes.plugin.v1.RouterPlugin.OrderCandidates:input_type -> gateyes.plugin.v1.OrderCandidatesRequest
	3, // 3: gateyes.plugin.v1.RouterPlugin.OrderCandidates:output_type -> gateyes.plugin.v1.OrderCandidatesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_router_proto_init() }
func file_proto_plugin_v1_router_proto_init() {
	if File_proto_plugin_v1_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_router_proto_rawDesc), len(file_proto_plugin_v1_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_v1_router_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_router_proto_depIdxs,
		MessageInfos:      file_proto_plugin_v1_router_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_router_proto = out.File
	file_proto_plugin_v1_router_proto_goTypes = nil
	file_proto_plugin_v1_router_proto_depIdxs = nil
}
