// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/control/v1/runtime_config.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlErrorCode int32

const (
	ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED        ControlErrorCode = 0
	ControlErrorCode_CONTROL_ERROR_CODE_INVALID_REQUEST    ControlErrorCode = 1
	ControlErrorCode_CONTROL_ERROR_CODE_REVISION_NOT_FOUND ControlErrorCode = 2
	ControlErrorCode_CONTROL_ERROR_CODE_UNAVAILABLE        ControlErrorCode = 3
	ControlErrorCode_CONTROL_ERROR_CODE_INTERNAL           ControlErrorCode = 4
)

// Enum value maps for ControlErrorCode.
var (
	ControlErrorCode_name = map[int32]string{
		0: "CONTROL_ERROR_CODE_UNSPECIFIED",
		1: "CONTROL_ERROR_CODE_INVALID_REQUEST",
		2: "CONTROL_ERROR_CODE_REVISION_NOT_FOUND",
		3: "CONTROL_ERROR_CODE_UNAVAILABLE",
		4: "CONTROL_ERROR_CODE_INTERNAL",
	}
	ControlErrorCode_value = map[string]int32{
		"CONTROL_ERROR_CODE_UNSPECIFIED":        0,
		"CONTROL_ERROR_CODE_INVALID_REQUEST":    1,
		"CONTROL_ERROR_CODE_REVISION_NOT_FOUND": 2,
		"CONTROL_ERROR_CODE_UNAVAILABLE":        3,
		"CONTROL_ERROR_CODE_INTERNAL":           4,
	}
)

func (x ControlErrorCode) Enum() *ControlErrorCode {
	p := new(ControlErrorCode)
	*p = x
	return p
}

func (x ControlErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_v1_runtime_config_proto_enumTypes[0].Descriptor()
}

func (ControlErrorCode) Type() protoreflect.EnumType {
	return &file_proto_control_v1_runtime_config_proto_enumTypes[0]
}

func (x ControlErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlErrorCode.Descriptor instead.
func (ControlErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{0}
}

type SchemaVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersion) Reset() {
	*x = SchemaVersion{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersion) ProtoMessage() {}

func (x *SchemaVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersion.ProtoReflect.Descriptor instead.
func (*SchemaVersion) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SchemaVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type RequestMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetRuntimeSnapshotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion   *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata        *RequestMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	KnownRevisionId string                 `protobuf:"bytes,3,opt,name=known_revision_id,json=knownRevisionId,proto3" json:"known_revision_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRuntimeSnapshotRequest) Reset() {
	*x = GetRuntimeSnapshotRequest{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeSnapshotRequest) ProtoMessage() {}

func (x *GetRuntimeSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetRuntimeSnapshotRequest) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *GetRuntimeSnapshotRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRuntimeSnapshotRequest) GetKnownRevisionId() string {
	if x != nil {
		return x.KnownRevisionId
	}
	return ""
}

type GetRuntimeSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *RequestMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Snapshot      *RuntimeSnapshot       `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	NotModified   bool                   `protobuf:"varint,4,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	Error         *ControlErrorDetail    `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeSnapshotResponse) Reset() {
	*x = GetRuntimeSnapshotResponse{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeSnapshotResponse) ProtoMessage() {}

func (x *GetRuntimeSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetRuntimeSnapshotResponse) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *GetRuntimeSnapshotResponse) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRuntimeSnapshotResponse) GetSnapshot() *RuntimeSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GetRuntimeSnapshotResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *GetRuntimeSnapshotResponse) GetError() *ControlErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetRuntimeRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *RequestMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeRevisionRequest) Reset() {
	*x = GetRuntimeRevisionRequest{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeRevisionRequest) ProtoMessage() {}

func (x *GetRuntimeRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeRevisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetRuntimeRevisionRequest) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *GetRuntimeRevisionRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetRuntimeRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Metadata      *RequestMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Revision      *RuntimeRevision       `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Error         *ControlErrorDetail    `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeRevisionResponse) Reset() {
	*x = GetRuntimeRevisionResponse{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeRevisionResponse) ProtoMessage() {}

func (x *GetRuntimeRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeRevisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetRuntimeRevisionResponse) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *GetRuntimeRevisionResponse) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRuntimeRevisionResponse) GetRevision() *RuntimeRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *GetRuntimeRevisionResponse) GetError() *ControlErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RuntimeSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *RuntimeRevision       `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSnapshot) Reset() {
	*x = RuntimeSnapshot{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSnapshot) ProtoMessage() {}

func (x *RuntimeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSnapshot.ProtoReflect.Descriptor instead.
func (*RuntimeSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{6}
}

func (x *RuntimeSnapshot) GetRevision() *RuntimeRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *RuntimeSnapshot) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RuntimeSnapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RuntimeRevision struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RevisionId     string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	Generation     uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,4,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeRevision) Reset() {
	*x = RuntimeRevision{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeRevision) ProtoMessage() {}

func (x *RuntimeRevision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeRevision.ProtoReflect.Descriptor instead.
func (*RuntimeRevision) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeRevision) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *RuntimeRevision) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RuntimeRevision) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RuntimeRevision) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type ControlErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ControlErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=gateyes.control.v1.ControlErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlErrorDetail) Reset() {
	*x = ControlErrorDetail{}
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlErrorDetail) ProtoMessage() {}

func (x *ControlErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_v1_runtime_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlErrorDetail.ProtoReflect.Descriptor instead.
func (*ControlErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_control_v1_runtime_config_proto_rawDescGZIP(), []int{8}
}

func (x *ControlErrorDetail) GetCode() ControlErrorCode {
	if x != nil {
		return x.Code
	}
	return ControlErrorCode_CONTROL_ERROR_CODE_UNSPECIFIED
}

func (x *ControlErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_proto_control_v1_runtime_config_proto protoreflect.FileDescriptor

const file_proto_control_v1_runtime_config_proto_rawDesc = "" +
	"\n" +
	"%proto/control/v1/runtime_config.proto\x12\x12gateyes.control.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\rSchemaVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"h\n" +
	"\x0fRequestMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xd2\x01\n" +
	"\x19GetRuntimeSnapshotRequest\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.control.v1.SchemaVersionR\rschemaVersion\x12?\n" +
	"\bmetadata\x18\x02 \x01(\v2#.gateyes.control.v1.RequestMetadataR\bmetadata\x12*\n" +
	"\x11known_revision_id\x18\x03 \x01(\tR\x0fknownRevisionId\"\xc9\x02\n" +
	"\x1aGetRuntimeSnapshotResponse\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.control.v1.SchemaVersionR\rschemaVersion\x12?\n" +
	"\bmetadata\x18\x02 \x01(\v2#.gateyes.control.v1.RequestMetadataR\bmetadata\x12?\n" +
	"\bsnapshot\x18\x03 \x01(\v2#.gateyes.control.v1.RuntimeSnapshotR\bsnapshot\x12!\n" +
	"\fnot_modified\x18\x04 \x01(\bR\vnotModified\x12<\n" +
	"\x05error\x18\x05 \x01(\v2&.gateyes.control.v1.ControlErrorDetailR\x05error\"\xa6\x01\n" +
	"\x19GetRuntimeRevisionRequest\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.control.v1.SchemaVersionR\rschemaVersion\x12?\n" +
	"\bmetadata\x18\x02 \x01(\v2#.gateyes.control.v1.RequestMetadataR\bmetadata\"\xa6\x02\n" +
	"\x1aGetRuntimeRevisionResponse\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\v2!.gateyes.control.v1.SchemaVersionR\rschemaVersion\x12?\n" +
	"\bmetadata\x18\x02 \x01(\v2#.gateyes.control.v1.RequestMetadataR\bmetadata\x12?\n" +
	"\brevision\x18\x03 \x01(\v2#.gateyes.control.v1.RuntimeRevisionR\brevision\x12<\n" +
	"\x05error\x18\x04 \x01(\v2&.gateyes.control.v1.ControlErrorDetailR\x05error\"\x8f\x01\n" +
	"\x0fRuntimeSnapshot\x12?\n" +
	"\brevision\x18\x01 \x01(\v2#.gateyes.control.v1.RuntimeRevisionR\brevision\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xb6\x01\n" +
	"\x0fRuntimeRevision\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0fchecksum_sha256\x18\x04 \x01(\tR\x0echecksumSha256\"\x86\x01\n" +
	"\x12ControlErrorDetail\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.gateyes.control.v1.ControlErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*\xce\x01\n" +
	"\x10ControlErrorCode\x12\"\n" +
	"\x1eCONTROL_ERROR_CODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"CONTROL_ERROR_CODE_INVALID_REQUEST\x10\x01\x12)\n" +
	"%CONTROL_ERROR_CODE_REVISION_NOT_FOUND\x10\x02\x12\"\n" +
	"\x1eCONTROL_ERROR_CODE_UNAVAILABLE\x10\x03\x12\x1f\n" +
	"\x1bCONTROL_ERROR_CODE_INTERNAL\x10\x042\x80\x02\n" +
	"\x14RuntimeConfigService\x12s\n" +
	"\x12GetRuntimeSnapshot\x12-.gateyes.control.v1.GetRuntimeSnapshotRequest\x1a..gateyes.control.v1.GetRuntimeSnapshotResponse\x12s\n" +
	"\x12GetRuntimeRevision\x12-.gateyes.control.v1.GetRuntimeRevisionRequest\x1a..gateyes.control.v1.GetRuntimeRevisionResponseB5Z3github.com/gateyes/gateway/pkg/control/v1;controlv1b\x06proto3"

var (
	file_proto_control_v1_runtime_config_proto_rawDescOnce sync.Once
	file_proto_control_v1_runtime_config_proto_rawDescData []byte
)

func file_proto_control_v1_runtime_config_proto_rawDescGZIP() []byte {
	file_proto_control_v1_runtime_config_proto_rawDescOnce.Do(func() {
		file_proto_control_v1_runtime_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_v1_runtime_config_proto_rawDesc), len(file_proto_control_v1_runtime_config_proto_rawDesc)))
	})
	return file_proto_control_v1_runtime_config_proto_rawDescData
}

var file_proto_control_v1_runtime_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_control_v1_runtime_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_control_v1_runtime_config_proto_goTypes = []any{
	(ControlErrorCode)(0),              // 0: gateyes.control.v1.ControlErrorCode
	(*SchemaVersion)(nil),              // 1: gateyes.control.v1.SchemaVersion
	(*RequestMetadata)(nil),            // 2: gateyes.control.v1.RequestMetadata
	(*GetRuntimeSnapshotRequest)(nil),  // 3: gateyes.control.v1.GetRuntimeSnapshotRequest
	(*GetRuntimeSnapshotResponse)(nil), // 4: gateyes.control.v1.GetRuntimeSnapshotResponse
	(*GetRuntimeRevisionRequest)(nil),  // 5: gateyes.control.v1.GetRuntimeRevisionRequest
	(*GetRuntimeRevisionResponse)(nil), // 6: gateyes.control.v1.GetRuntimeRevisionResponse
	(*RuntimeSnapshot)(nil),            // 7: gateyes.control.v1.RuntimeSnapshot
	(*RuntimeRevision)(nil),            // 8: gateyes.control.v1.RuntimeRevision
	(*ControlErrorDetail)(nil),         // 9: gateyes.control.v1.ControlErrorDetail
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_proto_control_v1_runtime_config_proto_depIdxs = []int32{
	1,  // 0: gateyes.control.v1.GetRuntimeSnapshotRequest.schema_version:type_name -> gateyes.control.v1.SchemaVersion
	2,  // 1: gateyes.control.v1.GetRuntimeSnapshotRequest.metadata:type_name -> gateyes.control.v1.RequestMetadata
	1,  // 2: gateyes.control.v1.GetRuntimeSnapshotResponse.schema_version:type_name -> gateyes.control.v1.SchemaVersion
	2,  // 3: gateyes.control.v1.GetRuntimeSnapshotResponse.metadata:type_name -> gateyes.control.v1.RequestMetadata
	7,  // 4: gateyes.control.v1.GetRuntimeSnapshotResponse.snapshot:type_name -> gateyes.control.v1.RuntimeSnapshot
	9,  // 5: gateyes.control.v1.GetRuntimeSnapshotResponse.error:type_name -> gateyes.control.v1.ControlErrorDetail
	1,  // 6: gateyes.control.v1.GetRuntimeRevisionRequest.schema_version:type_name -> gateyes.control.v1.SchemaVersion
	2,  // 7: gateyes.control.v1.GetRuntimeRevisionRequest.metadata:type_name -> gateyes.control.v1.RequestMetadata
	1,  // 8: gateyes.control.v1.GetRuntimeRevisionResponse.schema_version:type_name -> gateyes.control.v1.SchemaVersion
	2,  // 9: gateyes.control.v1.GetRuntimeRevisionResponse.metadata:type_name -> gateyes.control.v1.RequestMetadata
	8,  // 10: gateyes.control.v1.GetRuntimeRevisionResponse.revision:type_name -> gateyes.control.v1.RuntimeRevision
	9,  // 11: gateyes.control.v1.GetRuntimeRevisionResponse.error:type_name -> gateyes.control.v1.ControlErrorDetail
	8,  // 12: gateyes.control.v1.RuntimeSnapshot.revision:type_name -> gateyes.control.v1.RuntimeRevision
	10, // 13: gateyes.control.v1.RuntimeRevision.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 14: gateyes.control.v1.ControlErrorDetail.code:type_name -> gateyes.control.v1.ControlErrorCode
	3,  // 15: gateyes.control.v1.RuntimeConfigService.GetRuntimeSnapshot:input_type -> gateyes.control.v1.GetRuntimeSnapshotRequest
	5,  // 16: gateyes.control.v1.RuntimeConfigService.GetRuntimeRevision:input_type -> gateyes.control.v1.GetRuntimeRevisionRequest
	4,  // 17: gateyes.control.v1.RuntimeConfigService.GetRuntimeSnapshot:output_type -> gateyes.control.v1.GetRuntimeSnapshotResponse
	6,  // 18: gateyes.control.v1.RuntimeConfigService.GetRuntimeRevision:output_type -> gateyes.control.v1.GetRuntimeRevisionResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_control_v1_runtime_config_proto_init() }
func file_proto_control_v1_runtime_config_proto_init() {
	if File_proto_control_v1_runtime_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_v1_runtime_config_proto_rawDesc), len(file_proto_control_v1_runtime_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_v1_runtime_config_proto_goTypes,
		DependencyIndexes: file_proto_control_v1_runtime_config_proto_depIdxs,
		EnumInfos:         file_proto_control_v1_runtime_config_proto_enumTypes,
		MessageInfos:      file_proto_control_v1_runtime_config_proto_msgTypes,
	}.Build()
	File_proto_control_v1_runtime_config_proto = out.File
	file_proto_control_v1_runtime_config_proto_goTypes = nil
	file_proto_control_v1_runtime_config_proto_depIdxs = nil
}
