// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/control/v1/runtime_config.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeConfigService_GetRuntimeSnapshot_FullMethodName = "/gateyes.control.v1.RuntimeConfigService/GetRuntimeSnapshot"
	RuntimeConfigService_GetRuntimeRevision_FullMethodName = "/gateyes.control.v1.RuntimeConfigService/GetRuntimeRevision"
)

// RuntimeConfigServiceClient is the client API for RuntimeConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeConfigService exposes versioned configuration snapshots to runtimes.
type RuntimeConfigServiceClient interface {
	// GetRuntimeSnapshot returns the latest snapshot or marks it unchanged.
	GetRuntimeSnapshot(ctx context.Context, in *GetRuntimeSnapshotRequest, opts ...grpc.CallOption) (*GetRuntimeSnapshotResponse, error)
	// GetRuntimeRevision returns lightweight revision metadata.
	GetRuntimeRevision(ctx context.Context, in *GetRuntimeRevisionRequest, opts ...grpc.CallOption) (*GetRuntimeRevisionResponse, error)
}

type runtimeConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeConfigServiceClient(cc grpc.ClientConnInterface) RuntimeConfigServiceClient {
	return &runtimeConfigServiceClient{cc}
}

func (c *runtimeConfigServiceClient) GetRuntimeSnapshot(ctx context.Context, in *GetRuntimeSnapshotRequest, opts ...grpc.CallOption) (*GetRuntimeSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeSnapshotResponse)
	err := c.cc.Invoke(ctx, RuntimeConfigService_GetRuntimeSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeConfigServiceClient) GetRuntimeRevision(ctx context.Context, in *GetRuntimeRevisionRequest, opts ...grpc.CallOption) (*GetRuntimeRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeRevisionResponse)
	err := c.cc.Invoke(ctx, RuntimeConfigService_GetRuntimeRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeConfigServiceServer is the server API for RuntimeConfigService service.
// All implementations must embed UnimplementedRuntimeConfigServiceServer
// for forward compatibility.
//
// RuntimeConfigService exposes versioned configuration snapshots to runtimes.
type RuntimeConfigServiceServer interface {
	// GetRuntimeSnapshot returns the latest snapshot or marks it unchanged.
	GetRuntimeSnapshot(context.Context, *GetRuntimeSnapshotRequest) (*GetRuntimeSnapshotResponse, error)
	// GetRuntimeRevision returns lightweight revision metadata.
	GetRuntimeRevision(context.Context, *GetRuntimeRevisionRequest) (*GetRuntimeRevisionResponse, error)
	mustEmbedUnimplementedRuntimeConfigServiceServer()
}

// UnimplementedRuntimeConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeConfigServiceServer struct{}

func (UnimplementedRuntimeConfigServiceServer) GetRuntimeSnapshot(context.Context, *GetRuntimeSnapshotRequest) (*GetRuntimeSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeSnapshot not implemented")
}
func (UnimplementedRuntimeConfigServiceServer) GetRuntimeRevision(context.Context, *GetRuntimeRevisionRequest) (*GetRuntimeRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeRevision not implemented")
}
func (UnimplementedRuntimeConfigServiceServer) mustEmbedUnimplementedRuntimeConfigServiceServer() {}
func (UnimplementedRuntimeConfigServiceServer) testEmbeddedByValue()                              {}

// UnsafeRuntimeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeConfigServiceServer will
// result in compilation errors.
type UnsafeRuntimeConfigServiceServer interface {
	mustEmbedUnimplementedRuntimeConfigServiceServer()
}

func RegisterRuntimeConfigServiceServer(s grpc.ServiceRegistrar, srv RuntimeConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeConfigService_ServiceDesc, srv)
}

func _RuntimeConfigService_GetRuntimeSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeConfigServiceServer).GetRuntimeSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeConfigService_GetRuntimeSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeConfigServiceServer).GetRuntimeSnapshot(ctx, req.(*GetRuntimeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeConfigService_GetRuntimeRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeConfigServiceServer).GetRuntimeRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeConfigService_GetRuntimeRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeConfigServiceServer).GetRuntimeRevision(ctx, req.(*GetRuntimeRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeConfigService_ServiceDesc is the grpc.ServiceDesc for RuntimeConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateyes.control.v1.RuntimeConfigService",
	HandlerType: (*RuntimeConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRuntimeSnapshot",
			Handler:    _RuntimeConfigService_GetRuntimeSnapshot_Handler,
		},
		{
			MethodName: "GetRuntimeRevision",
			Handler:    _RuntimeConfigService_GetRuntimeRevision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control/v1/runtime_config.proto",
}
